class IconDataManager {
  static final IconDataManager _instance = IconDataManager._();
  IconDataManager._();

  factory IconDataManager() => _instance;

  String getIconURL(String iconName) {
    return _iconData[iconName];
  }

  Map<String, List<String>> get iconCategoryData => _iconCategoryData;
  List<String> get availableCategories => [..._iconCategoryData.keys.toList()];

  List<String> getIconsOfCategory(String category) {
    if (_iconCategoryData.containsKey(category)) {
      return [..._iconCategoryData[category]];
    } else {
      return List<String>.empty();
    }
  }

  static const Map<String, String> _iconData = {
    'account': 'lib/assets/icons/account.png',
    'shoppingCart': 'lib/assets/icons/shoppingCart.png',
    'airport': 'lib/assets/icons/airport.png',
    'analytics': 'lib/assets/icons/analytics.png',
    'avocado': 'lib/assets/icons/avocado.png',
    'bank': 'lib/assets/icons/bank.png',
    'bar': 'lib/assets/icons/bar.png',
    'basketball': 'lib/assets/icons/basketball.png',
    'drum': 'lib/assets/icons/drum.png',
    'bathrobe': 'lib/assets/icons/bathrobe.png',
    'beer': 'lib/assets/icons/beer.png',
    'reading': 'lib/assets/icons/reading.png',
    'bowling': 'lib/assets/icons/bowling.png',
    'boxing': 'lib/assets/icons/boxing.png',
    'broccoli': 'lib/assets/icons/broccoli.png',
    'broom': 'lib/assets/icons/broom.png',
    'bug': 'lib/assets/icons/bug.png',
    'bus': 'lib/assets/icons/bus.png',
    'business': 'lib/assets/icons/business.png',
    'creditCard': 'lib/assets/icons/creditCard.png',
    'classroom': 'lib/assets/icons/classroom.png',
    'closedEye': 'lib/assets/icons/closedEye.png',
    'cocktail': 'lib/assets/icons/cocktail.png',
    'comedy': 'lib/assets/icons/comedy.png',
    'confetti': 'lib/assets/icons/confetti.png',
    'console': 'lib/assets/icons/console.png',
    'crowd': 'lib/assets/icons/crowd.png',
    'cuttingBoard': 'lib/assets/icons/cuttingBoard.png',
    'dataCenter': 'lib/assets/icons/dataCenter.png',
    'pets': 'lib/assets/icons/pets.png',
    'peace': 'lib/assets/icons/peace.png',
    'trash': 'lib/assets/icons/trash.png',
    'family': 'lib/assets/icons/family.png',
    'mobileShop': 'lib/assets/icons/mobileShop.png',
    'gameController': 'lib/assets/icons/gameController.png',
    'football': 'lib/assets/icons/football.png',
    'guitar': 'lib/assets/icons/guitar.png',
    'gymnastics': 'lib/assets/icons/gymnastics.png',
    'hamburger': 'lib/assets/icons/hamburger.png',
    'hammer': 'lib/assets/icons/hammer.png',
    'simpson': 'lib/assets/icons/simpson.png',
    'bed': 'lib/assets/icons/bed.png',
    'hourglass': 'lib/assets/icons/hourglass.png',
    'ideation': 'lib/assets/icons/ideation.png',
    'logistics': 'lib/assets/icons/logistics.png',
    'innovation': 'lib/assets/icons/innovation.png',
    'bread': 'lib/assets/icons/bread.png',
    'coffee': 'lib/assets/icons/coffee.png',
    'cupcake': 'lib/assets/icons/cupcake.png',
    'egg': 'lib/assets/icons/egg.png',
    'frenchFries': 'lib/assets/icons/frenchFries.png',
    'iceCream': 'lib/assets/icons/iceCream.png',
    'pizza': 'lib/assets/icons/pizza.png',
    'steak': 'lib/assets/icons/steak.png',
    'laptop': 'lib/assets/icons/laptop.png',
    'mail': 'lib/assets/icons/mail.png',
    'meeting': 'lib/assets/icons/meeting.png',
    'music': 'lib/assets/icons/music.png',
    'netflix': 'lib/assets/icons/netflix.png',
    'swimming': 'lib/assets/icons/swimming.png',
    'art': 'lib/assets/icons/art.png',
    'party': 'lib/assets/icons/party.png',
    'layingDown': 'lib/assets/icons/layingDown.png',
    'piano': 'lib/assets/icons/piano.png',
    'planner': 'lib/assets/icons/planner.png',
    'popcorn': 'lib/assets/icons/popcorn.png',
    'powerPlant': 'lib/assets/icons/powerPlant.png',
    'restaurant': 'lib/assets/icons/restaurant.png',
    'retroTV': 'lib/assets/icons/retroTV.png',
    'romance': 'lib/assets/icons/romance.png',
    'santa': 'lib/assets/icons/santa.png',
    'school': 'lib/assets/icons/school.png',
    'groceryShopping': 'lib/assets/icons/groceryShopping.png',
    'browsingPhone': 'lib/assets/icons/browsingPhone.png',
    'spotify': 'lib/assets/icons/spotify.png',
    'strengthTraining': 'lib/assets/icons/strengthTraining.png',
    'student': 'lib/assets/icons/student.png',
    'subway': 'lib/assets/icons/subway.png',
    'sunnySideUp': 'lib/assets/icons/sunnySideUp.png',
    'sunRise': 'lib/assets/icons/sunRise.png',
    'survey': 'lib/assets/icons/survey.png',
    'cheers': 'lib/assets/icons/cheers.png',
    'running': 'lib/assets/icons/running.png',
    'driving': 'lib/assets/icons/driving.png',
    'train': 'lib/assets/icons/train.png',
    'videoConferencing': 'lib/assets/icons/videoConferencing.png',
    'digitalArt': 'lib/assets/icons/digitalArt.png',
    'walking': 'lib/assets/icons/walking.png',
    'ship': 'lib/assets/icons/ship.png',
    'whatsapp': 'lib/assets/icons/whatsapp.png',
    'workStation': 'lib/assets/icons/workStation.png',
    'zen': 'lib/assets/icons/zen.png',
  };

  static const Map<String, List<String>> _iconCategoryData = {
    'Sleep': [
      'closedEye',
      'bed',
      'sunRise',
    ],
    'Work': [
      'account',
      'analytics',
      'bug',
      'business',
      'console',
      'dataCenter',
      'ideation',
      'logistics',
      'innovation',
      'laptop',
      'mail',
      'meeting',
      'planner',
      'powerPlant',
      'survey',
      'videoConferencing',
      'digitalArt',
      'workStation',
    ],
    'Learn': [
      'classroom',
      'school',
      'student',
    ],
    'Travel': [
      'airport',
      'bus',
      'subway',
      'driving',
      'train',
      'ship',
    ],
    'Food': [
      'avocado',
      'broccoli',
      'hamburger',
      'bread',
      'coffee',
      'cupcake',
      'egg',
      'frenchFries',
      'iceCream',
      'pizza',
      'steak',
      'sunnySideUp',
    ],
    'Leisure': [
      'shoppingCart',
      'drum',
      'reading',
      'bowling',
      'comedy',
      'confetti',
      'mobileShop',
      'gameController',
      'guitar',
      'simpson',
      'music',
      'netflix',
      'art',
      'layingDown',
      'piano',
      'restaurant',
      'retroTV',
      'browsingPhone',
      'spotify',
      'whatsapp',
    ],
    'Exercise': [
      'basketball',
      'boxing',
      'peace',
      'football',
      'gymnastics',
      'swimming',
      'strengthTraining',
      'running',
      'walking',
      'zen',
    ],
    'Social': [
      'bar',
      'beer',
      'cocktail',
      'crowd',
      'pets',
      'family',
      'party',
      'popcorn',
      'romance',
      'santa',
      'cheers',
    ],
    'Miscellaneous': [
      'bank',
      'bathrobe',
      'broom',
      'creditCard',
      'cuttingBoard',
      'trash',
      'hammer',
      'hourglass',
      'groceryShopping',
    ],
  };
}
